apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: q1jomq3lw-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/q1jomq3lw-java-springboot-gitops